// <auto-generated />
#nullable enable
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace MonomytoChallenge.Models
{
    public enum ClassificacaoType : byte
    {
        Prata,
        Ouro,
        Pura,
    }

    public class Produto
    {
        public Guid Id { get; set; }

        public string? Marca { get; set; }

        [JsonConverter(typeof(StringEnumConverter))]
        public ClassificacaoType Classificacao { get; set; }

        public string? Nome { get; set; }

        public int TeorAlcoolico { get; set; }

        public string? Regiao { get; set; }

        public float PrecoAtual { get; set; }

        // Relationship
        public virtual ICollection<Item>? Vendas { get; set; }
    }

    public class ProdutoReport
    {
        public Produto? Produto;

        public float TotalValor { get; set; }

        public int TotalQuantidade { get; set; }
    }
}
