// <auto-generated />
#nullable enable


namespace MonomytoChallenge.Models
{
    public class Venda
    {
        public Guid Id { get; set; }

        public DateTime Data { get; set; }

        // Relationship
        public Guid IdCliente { get; set; }
        public virtual Cliente? Cliente { get; set; }

        public virtual ICollection<Item>? Itens { get; set; }
    }

    public class VendaReport
    {
        public Guid Id { get; set; }

        public DateTime Data { get; set; }

        public Guid IdCliente { get; set; }

        public virtual Cliente? Cliente { get; set; }

        public virtual IEnumerable<ItemVenda>? Itens { get; set; }
    }
}
