version: '3.4'

services:
  monomytochallenge:
    image: monomytochallenge:latest
    build:
      context: .
      dockerfile: MonomytoChallenge/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    environment:
        ASPNETCORE_URLS: "http://+"
        ASPNETCORE_ENVIRONMENT: "Development"
        