version: '3.4'

services:
  monomytochallenge:
    image: monomytochallenge:latest
    build:
      context: .
      dockerfile: MonomytoChallenge/Dockerfile
    ports:
        - "5000:80"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_URLS: "http://+:80"