// <auto-generated />
#nullable enable
using FluentValidation;
using MonomytoChallenge.Models;


namespace MonomytoChallenge.Validators
{
    public class ClienteValidator : AbstractValidator<Cliente>
    {
        public ClienteValidator()
        {
            this.RuleFor(c => c.Id)
                .NotEmpty().WithMessage("Requer a inserção do ID.");

            this.RuleFor(c => c.Nome)
                .NotEmpty().WithMessage("Requer a inserção do Nome.");

            this.RuleFor(c => c.DataNascimento)
                .NotEmpty().WithMessage("Requer a inserção da Data de Nascimento.");
        }
    }
}
