// <auto-generated />
#nullable enable
using FluentValidation;
using MonomytoChallenge.Models;


namespace MonomytoChallenge.Validators
{
    public class ItemValidator : AbstractValidator<Item>
    {
        public ItemValidator()
        {
            this.RuleFor(i => i.Id)
                .NotEmpty().WithMessage("Requer a inserção do Id.");

            this.RuleFor(i => i.PrecoUnitario)
                .NotEmpty().WithMessage("Requer a inserção do Preço Unitário.");

            this.RuleFor(i => i.Quantidade)
                .NotEmpty().WithMessage("Requer a inserção da Quantidade.");

            this.RuleFor(i => i.IdProduto)
                .NotEmpty().WithMessage("Requer a inserção do ID do Produto.");

            this.RuleFor(i => i.IdVenda)
                .NotEmpty().WithMessage("Requer a inserção do ID da Venda.");
        }
    }
}
