// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MonomytoChallenge.Models;


namespace MonomytoChallenge.Configurations
{
    //  Realiza a configuração dos campos da entidade Cliente
    public class ClienteConfiguration : IEntityTypeConfiguration<Cliente>
    {
        public void Configure(EntityTypeBuilder<Cliente> builder)
        {
            builder.HasKey(c => c.Id);
            builder.Property(c => c.Id)
                .IsRequired();

            builder.Property(c => c.Nome)
                .IsRequired();

            builder.Property(c => c.DataNascimento)
                .IsRequired()
                .HasColumnType("Date");

            builder.HasMany(c => c.Compras)
                .WithOne(v => v.Cliente);
        }
    }
}
