// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MonomytoChallenge.Models;


namespace MonomytoChallenge.Configurations
{
    //  Realiza a configuração dos campos da entidade Produto
    public class ProdutoConfiguration : IEntityTypeConfiguration<Produto>
    {
        public void Configure(EntityTypeBuilder<Produto> builder)
        {
            builder.HasKey(p => p.Id);
            builder.Property(p => p.Id)
                .IsRequired();

            builder.Property(p => p.Marca)
                .IsRequired();

            builder.Property(p => p.Classificacao)
                .HasDefaultValue(ClassificacaoType.Prata);

            builder.Property(p => p.Nome)
                .IsRequired();

            builder.Property(p => p.TeorAlcoolico)
                .IsRequired();

            builder.Property(p => p.Regiao)
                .IsRequired()
                .HasMaxLength(2);

            builder.Property(p => p.PrecoAtual)
                .IsRequired()
                .HasPrecision(5, 2);

            builder.HasMany(p => p.Vendas)
                .WithOne(i => i.Produto);
        }
    }
}
