// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MonomytoChallenge.Models;


namespace MonomytoChallenge.Configurations
{
    //  Realiza a configuração dos campos da entidade Venda
    public class VendaConfiguration : IEntityTypeConfiguration<Venda>
    {
        public void Configure(EntityTypeBuilder<Venda> builder)
        {
            builder.HasKey(v => v.Id);
            builder.Property(v => v.Id)
                .IsRequired();

            builder.Property(v => v.Data)
                .IsRequired()
                .HasColumnType("Date");

            builder.HasOne(v => v.Cliente)
                .WithMany(c => c.Compras)
                .HasForeignKey(v => v.IdCliente);

            builder.HasMany(v => v.Itens)
                .WithOne(i => i.Venda);
        }
    }
}
